In [1]:
import numpy as np
array1 = np.array(range(2,6))
print(array1)
array2 = np.array([[1,3],[4,6]])
print(array2)

[2 3 4 5]
[[1 3]
 [4 6]]


In [2]:
import numpy as np

data = np.random.rand(6)
print(data)

[0.75513892 0.39764472 0.61668759 0.3636494  0.68036835 0.66394635]


In [3]:
import numpy as np

data = np.random.rand(2,4)
print(data)

[[0.61251597 0.73832464 0.50569918 0.38113989]
 [0.45356967 0.49973037 0.03844349 0.87992981]]


In [4]:
import numpy as np

data = np.random.uniform(1,10,(2,4))
print(data)

[[3.98526178 6.05004445 1.11352346 4.26879569]
 [6.98113569 4.43638812 9.48662199 5.37304313]]


In [5]:
import numpy as np

data = np.array([[2,4,6],[3,5,7],[8,6,4]])
print(data)

[[2 4 6]
 [3 5 7]
 [8 6 4]]


In [7]:
import numpy as np

d_array = [[2,4,6],[3,5,7],[8,6,4]]
print(type(d_array))
print('list of d_array')
print(d_array)

data = np.array(d_array)
print(type(data))
print('data is')
print(data)

<class 'list'>
list of d_array
[[2, 4, 6], [3, 5, 7], [8, 6, 4]]
<class 'numpy.ndarray'>
data is
[[2 4 6]
 [3 5 7]
 [8 6 4]]


In [10]:
import numpy as np

data_array = np.arange(10)
print(data_array)

d_array = np.linspace(1,9,6)
print(d_array)

data_array_zero = np.zeros((3,2),dtype = np.int32)
print(data_array_zero)

data_array_one = np.ones((3,2),dtype = np.int32)
print(data_array_one)

[0 1 2 3 4 5 6 7 8 9]
[1.  2.6 4.2 5.8 7.4 9. ]
[[0 0]
 [0 0]
 [0 0]]
[[1 1]
 [1 1]
 [1 1]]


In [11]:
import numpy as np

i_matrix = np.identity(3,dtype = np.int64)
print(i_matrix)
i_matrix_2 = np.eye(3,dtype = np.int64)
print(i_matrix_2)
i_matrix_3 = np.eye(3,4,dtype = np.int64)
print(i_matrix_3)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]
